-- LMN24 - Seed des pays
-- Source de référence des codes : ISO 3166-1 via pycountry
-- 249 entrées (pays et territoires disposant d'un code ISO 3166-1).
-- Le script est réexécutable : les lignes existantes sont mises à jour via iso_code2.

BEGIN;

INSERT INTO country (name, iso_code2, iso_code3, slug, is_active)
VALUES
    ('Afghanistan', 'AF', 'AFG', 'afghanistan', TRUE),
    ('Afrique du Sud', 'ZA', 'ZAF', 'afrique-du-sud', TRUE),
    ('Albanie', 'AL', 'ALB', 'albanie', TRUE),
    ('Algérie', 'DZ', 'DZA', 'algerie', TRUE),
    ('Allemagne', 'DE', 'DEU', 'allemagne', TRUE),
    ('Andorre', 'AD', 'AND', 'andorre', TRUE),
    ('Angola', 'AO', 'AGO', 'angola', TRUE),
    ('Anguilla', 'AI', 'AIA', 'anguilla', TRUE),
    ('Antarctique', 'AQ', 'ATA', 'antarctique', TRUE),
    ('Antigua-et-Barbuda', 'AG', 'ATG', 'antigua-et-barbuda', TRUE),
    ('Arabie saoudite', 'SA', 'SAU', 'arabie-saoudite', TRUE),
    ('Argentine', 'AR', 'ARG', 'argentine', TRUE),
    ('Arménie', 'AM', 'ARM', 'armenie', TRUE),
    ('Aruba', 'AW', 'ABW', 'aruba', TRUE),
    ('Australie', 'AU', 'AUS', 'australie', TRUE),
    ('Autriche', 'AT', 'AUT', 'autriche', TRUE),
    ('Azerbaïdjan', 'AZ', 'AZE', 'azerbaidjan', TRUE),
    ('Bahamas', 'BS', 'BHS', 'bahamas', TRUE),
    ('Bahreïn', 'BH', 'BHR', 'bahrein', TRUE),
    ('Bangladesh', 'BD', 'BGD', 'bangladesh', TRUE),
    ('Barbade', 'BB', 'BRB', 'barbade', TRUE),
    ('Belgique', 'BE', 'BEL', 'belgique', TRUE),
    ('Belize', 'BZ', 'BLZ', 'belize', TRUE),
    ('Bermudes', 'BM', 'BMU', 'bermudes', TRUE),
    ('Bhoutan', 'BT', 'BTN', 'bhoutan', TRUE),
    ('Birmanie', 'MM', 'MMR', 'birmanie', TRUE),
    ('Bolivie, état plurinational de', 'BO', 'BOL', 'bolivie-etat-plurinational-de', TRUE),
    ('Bonaire, Saint-Eustache et Saba', 'BQ', 'BES', 'bonaire-saint-eustache-et-saba', TRUE),
    ('Bosnie-Herzégovine', 'BA', 'BIH', 'bosnie-herzegovine', TRUE),
    ('Botswana', 'BW', 'BWA', 'botswana', TRUE),
    ('Brunéi Darussalam', 'BN', 'BRN', 'brunei-darussalam', TRUE),
    ('Brésil', 'BR', 'BRA', 'bresil', TRUE),
    ('Bulgarie', 'BG', 'BGR', 'bulgarie', TRUE),
    ('Burkina Faso', 'BF', 'BFA', 'burkina-faso', TRUE),
    ('Burundi', 'BI', 'BDI', 'burundi', TRUE),
    ('Bélarus', 'BY', 'BLR', 'belarus', TRUE),
    ('Bénin', 'BJ', 'BEN', 'benin', TRUE),
    ('Cambodge', 'KH', 'KHM', 'cambodge', TRUE),
    ('Cameroun', 'CM', 'CMR', 'cameroun', TRUE),
    ('Canada', 'CA', 'CAN', 'canada', TRUE),
    ('Cap-Vert', 'CV', 'CPV', 'cap-vert', TRUE),
    ('Chili', 'CL', 'CHL', 'chili', TRUE),
    ('Chine', 'CN', 'CHN', 'chine', TRUE),
    ('Christmas, Île', 'CX', 'CXR', 'christmas-ile', TRUE),
    ('Chypre', 'CY', 'CYP', 'chypre', TRUE),
    ('Cocos (Keeling), Îles', 'CC', 'CCK', 'cocos-keeling-iles', TRUE),
    ('Colombie', 'CO', 'COL', 'colombie', TRUE),
    ('Comores', 'KM', 'COM', 'comores', TRUE),
    ('Corée, République de', 'KR', 'KOR', 'coree-republique-de', TRUE),
    ('Corée, République populaire démocratique de', 'KP', 'PRK', 'coree-republique-populaire-democratique-de', TRUE),
    ('Costa Rica', 'CR', 'CRI', 'costa-rica', TRUE),
    ('Croatie', 'HR', 'HRV', 'croatie', TRUE),
    ('Cuba', 'CU', 'CUB', 'cuba', TRUE),
    ('Curaçao', 'CW', 'CUW', 'curacao', TRUE),
    ('Côte d''Ivoire', 'CI', 'CIV', 'cote-d-ivoire', TRUE),
    ('Danemark', 'DK', 'DNK', 'danemark', TRUE),
    ('Djibouti', 'DJ', 'DJI', 'djibouti', TRUE),
    ('Dominique', 'DM', 'DMA', 'dominique', TRUE),
    ('Espagne', 'ES', 'ESP', 'espagne', TRUE),
    ('Estonie', 'EE', 'EST', 'estonie', TRUE),
    ('Eswatini', 'SZ', 'SWZ', 'eswatini', TRUE),
    ('Fidji', 'FJ', 'FJI', 'fidji', TRUE),
    ('Finlande', 'FI', 'FIN', 'finlande', TRUE),
    ('France', 'FR', 'FRA', 'france', TRUE),
    ('Gabon', 'GA', 'GAB', 'gabon', TRUE),
    ('Gambie', 'GM', 'GMB', 'gambie', TRUE),
    ('Ghana', 'GH', 'GHA', 'ghana', TRUE),
    ('Gibraltar', 'GI', 'GIB', 'gibraltar', TRUE),
    ('Grenade', 'GD', 'GRD', 'grenade', TRUE),
    ('Groënland', 'GL', 'GRL', 'groenland', TRUE),
    ('Grèce', 'GR', 'GRC', 'grece', TRUE),
    ('Guadeloupe', 'GP', 'GLP', 'guadeloupe', TRUE),
    ('Guam', 'GU', 'GUM', 'guam', TRUE),
    ('Guatemala', 'GT', 'GTM', 'guatemala', TRUE),
    ('Guernesey', 'GG', 'GGY', 'guernesey', TRUE),
    ('Guinée', 'GN', 'GIN', 'guinee', TRUE),
    ('Guinée Équatoriale', 'GQ', 'GNQ', 'guinee-equatoriale', TRUE),
    ('Guinée-Bissau', 'GW', 'GNB', 'guinee-bissau', TRUE),
    ('Guyana', 'GY', 'GUY', 'guyana', TRUE),
    ('Guyane française', 'GF', 'GUF', 'guyane-francaise', TRUE),
    ('Géorgie', 'GE', 'GEO', 'georgie', TRUE),
    ('Géorgie du Sud et les îles Sandwich du Sud', 'GS', 'SGS', 'georgie-du-sud-et-les-iles-sandwich-du-sud', TRUE),
    ('Haïti', 'HT', 'HTI', 'haiti', TRUE),
    ('Honduras', 'HN', 'HND', 'honduras', TRUE),
    ('Hong Kong', 'HK', 'HKG', 'hong-kong', TRUE),
    ('Hongrie', 'HU', 'HUN', 'hongrie', TRUE),
    ('Inde', 'IN', 'IND', 'inde', TRUE),
    ('Indonésie', 'ID', 'IDN', 'indonesie', TRUE),
    ('Irak', 'IQ', 'IRQ', 'irak', TRUE),
    ('Iran, République islamique d''', 'IR', 'IRN', 'iran-republique-islamique-d', TRUE),
    ('Irlande', 'IE', 'IRL', 'irlande', TRUE),
    ('Islande', 'IS', 'ISL', 'islande', TRUE),
    ('Israël', 'IL', 'ISR', 'israel', TRUE),
    ('Italie', 'IT', 'ITA', 'italie', TRUE),
    ('Jamaïque', 'JM', 'JAM', 'jamaique', TRUE),
    ('Japon', 'JP', 'JPN', 'japon', TRUE),
    ('Jersey', 'JE', 'JEY', 'jersey', TRUE),
    ('Jordanie', 'JO', 'JOR', 'jordanie', TRUE),
    ('Kazakhstan', 'KZ', 'KAZ', 'kazakhstan', TRUE),
    ('Kenya', 'KE', 'KEN', 'kenya', TRUE),
    ('Kirghizistan', 'KG', 'KGZ', 'kirghizistan', TRUE),
    ('Kiribati', 'KI', 'KIR', 'kiribati', TRUE),
    ('Koweït', 'KW', 'KWT', 'koweit', TRUE),
    ('Lao, République démocratique populaire', 'LA', 'LAO', 'lao-republique-democratique-populaire', TRUE),
    ('Lesotho', 'LS', 'LSO', 'lesotho', TRUE),
    ('Lettonie', 'LV', 'LVA', 'lettonie', TRUE),
    ('Liban', 'LB', 'LBN', 'liban', TRUE),
    ('Libye', 'LY', 'LBY', 'libye', TRUE),
    ('Libéria', 'LR', 'LBR', 'liberia', TRUE),
    ('Liechtenstein', 'LI', 'LIE', 'liechtenstein', TRUE),
    ('Lituanie', 'LT', 'LTU', 'lituanie', TRUE),
    ('Luxembourg', 'LU', 'LUX', 'luxembourg', TRUE),
    ('Macau', 'MO', 'MAC', 'macau', TRUE),
    ('Macédoine du Nord', 'MK', 'MKD', 'macedoine-du-nord', TRUE),
    ('Madagascar', 'MG', 'MDG', 'madagascar', TRUE),
    ('Malaisie', 'MY', 'MYS', 'malaisie', TRUE),
    ('Malawi', 'MW', 'MWI', 'malawi', TRUE),
    ('Maldives', 'MV', 'MDV', 'maldives', TRUE),
    ('Mali', 'ML', 'MLI', 'mali', TRUE),
    ('Malouines, Îles (Falkland)', 'FK', 'FLK', 'malouines-iles-falkland', TRUE),
    ('Malte', 'MT', 'MLT', 'malte', TRUE),
    ('Maroc', 'MA', 'MAR', 'maroc', TRUE),
    ('Martinique', 'MQ', 'MTQ', 'martinique', TRUE),
    ('Maurice', 'MU', 'MUS', 'maurice', TRUE),
    ('Mauritanie', 'MR', 'MRT', 'mauritanie', TRUE),
    ('Mayotte', 'YT', 'MYT', 'mayotte', TRUE),
    ('Mexique', 'MX', 'MEX', 'mexique', TRUE),
    ('Micronésie, États fédérés de', 'FM', 'FSM', 'micronesie-etats-federes-de', TRUE),
    ('Moldova, République de', 'MD', 'MDA', 'moldova-republique-de', TRUE),
    ('Monaco', 'MC', 'MCO', 'monaco', TRUE),
    ('Mongolie', 'MN', 'MNG', 'mongolie', TRUE),
    ('Montserrat', 'MS', 'MSR', 'montserrat', TRUE),
    ('Monténégro', 'ME', 'MNE', 'montenegro', TRUE),
    ('Mozambique', 'MZ', 'MOZ', 'mozambique', TRUE),
    ('Namibie', 'NA', 'NAM', 'namibie', TRUE),
    ('Nauru', 'NR', 'NRU', 'nauru', TRUE),
    ('Nicaragua', 'NI', 'NIC', 'nicaragua', TRUE),
    ('Niger', 'NE', 'NER', 'niger', TRUE),
    ('Nigeria', 'NG', 'NGA', 'nigeria', TRUE),
    ('Nioue', 'NU', 'NIU', 'nioue', TRUE),
    ('Norvège', 'NO', 'NOR', 'norvege', TRUE),
    ('Nouvelle-Calédonie', 'NC', 'NCL', 'nouvelle-caledonie', TRUE),
    ('Nouvelle-Zélande', 'NZ', 'NZL', 'nouvelle-zelande', TRUE),
    ('Népal', 'NP', 'NPL', 'nepal', TRUE),
    ('Oman', 'OM', 'OMN', 'oman', TRUE),
    ('Ouganda', 'UG', 'UGA', 'ouganda', TRUE),
    ('Ouzbékistan', 'UZ', 'UZB', 'ouzbekistan', TRUE),
    ('Pakistan', 'PK', 'PAK', 'pakistan', TRUE),
    ('Palaos', 'PW', 'PLW', 'palaos', TRUE),
    ('Palestine, État de', 'PS', 'PSE', 'palestine-etat-de', TRUE),
    ('Panama', 'PA', 'PAN', 'panama', TRUE),
    ('Papouasie-Nouvelle-Guinée', 'PG', 'PNG', 'papouasie-nouvelle-guinee', TRUE),
    ('Paraguay', 'PY', 'PRY', 'paraguay', TRUE),
    ('Pays-Bas', 'NL', 'NLD', 'pays-bas', TRUE),
    ('Philippines', 'PH', 'PHL', 'philippines', TRUE),
    ('Pologne', 'PL', 'POL', 'pologne', TRUE),
    ('Polynésie française', 'PF', 'PYF', 'polynesie-francaise', TRUE),
    ('Porto Rico', 'PR', 'PRI', 'porto-rico', TRUE),
    ('Portugal', 'PT', 'PRT', 'portugal', TRUE),
    ('Pérou', 'PE', 'PER', 'perou', TRUE),
    ('Qatar', 'QA', 'QAT', 'qatar', TRUE),
    ('Roumanie', 'RO', 'ROU', 'roumanie', TRUE),
    ('Royaume-Uni', 'GB', 'GBR', 'royaume-uni', TRUE),
    ('Russie, Fédération de', 'RU', 'RUS', 'russie-federation-de', TRUE),
    ('Rwanda', 'RW', 'RWA', 'rwanda', TRUE),
    ('République centrafricaine', 'CF', 'CAF', 'republique-centrafricaine', TRUE),
    ('République dominicaine', 'DO', 'DOM', 'republique-dominicaine', TRUE),
    ('République du Congo', 'CG', 'COG', 'republique-du-congo', TRUE),
    ('République démocratique du Congo', 'CD', 'COD', 'republique-democratique-du-congo', TRUE),
    ('Réunion, Île de la', 'RE', 'REU', 'reunion-ile-de-la', TRUE),
    ('Sahara occidental', 'EH', 'ESH', 'sahara-occidental', TRUE),
    ('Saint-Barthélemy', 'BL', 'BLM', 'saint-barthelemy', TRUE),
    ('Saint-Christophe-et-Niévès', 'KN', 'KNA', 'saint-christophe-et-nieves', TRUE),
    ('Saint-Marin', 'SM', 'SMR', 'saint-marin', TRUE),
    ('Saint-Martin (partie française)', 'MF', 'MAF', 'saint-martin-partie-francaise', TRUE),
    ('Saint-Martin (partie néerlandaise)', 'SX', 'SXM', 'saint-martin-partie-neerlandaise', TRUE),
    ('Saint-Pierre-et-Miquelon', 'PM', 'SPM', 'saint-pierre-et-miquelon', TRUE),
    ('Saint-Siège (état de la cité du Vatican)', 'VA', 'VAT', 'saint-siege-etat-de-la-cite-du-vatican', TRUE),
    ('Saint-Vincent-et-les-Grenadines', 'VC', 'VCT', 'saint-vincent-et-les-grenadines', TRUE),
    ('Sainte-Hélène, Ascension et Tristan da Cunha', 'SH', 'SHN', 'sainte-helene-ascension-et-tristan-da-cunha', TRUE),
    ('Sainte-Lucie', 'LC', 'LCA', 'sainte-lucie', TRUE),
    ('Salomon, Îles', 'SB', 'SLB', 'salomon-iles', TRUE),
    ('Salvador', 'SV', 'SLV', 'salvador', TRUE),
    ('Samoa', 'WS', 'WSM', 'samoa', TRUE),
    ('Samoa américaines', 'AS', 'ASM', 'samoa-americaines', TRUE),
    ('Sao Tomé-et-Principe', 'ST', 'STP', 'sao-tome-et-principe', TRUE),
    ('Serbie', 'RS', 'SRB', 'serbie', TRUE),
    ('Seychelles', 'SC', 'SYC', 'seychelles', TRUE),
    ('Sierra Leone', 'SL', 'SLE', 'sierra-leone', TRUE),
    ('Singapour', 'SG', 'SGP', 'singapour', TRUE),
    ('Slovaquie', 'SK', 'SVK', 'slovaquie', TRUE),
    ('Slovénie', 'SI', 'SVN', 'slovenie', TRUE),
    ('Somalie', 'SO', 'SOM', 'somalie', TRUE),
    ('Soudan', 'SD', 'SDN', 'soudan', TRUE),
    ('Soudan du Sud', 'SS', 'SSD', 'soudan-du-sud', TRUE),
    ('Sri Lanka', 'LK', 'LKA', 'sri-lanka', TRUE),
    ('Suisse', 'CH', 'CHE', 'suisse', TRUE),
    ('Surinam', 'SR', 'SUR', 'surinam', TRUE),
    ('Suède', 'SE', 'SWE', 'suede', TRUE),
    ('Svalbard et île Jan Mayen', 'SJ', 'SJM', 'svalbard-et-ile-jan-mayen', TRUE),
    ('Syrienne, République arabe', 'SY', 'SYR', 'syrienne-republique-arabe', TRUE),
    ('Sénégal', 'SN', 'SEN', 'senegal', TRUE),
    ('Tadjikistan', 'TJ', 'TJK', 'tadjikistan', TRUE),
    ('Tanzanie, République unie de', 'TZ', 'TZA', 'tanzanie-republique-unie-de', TRUE),
    ('Taïwan, province de Chine', 'TW', 'TWN', 'taiwan-province-de-chine', TRUE),
    ('Tchad', 'TD', 'TCD', 'tchad', TRUE),
    ('Tchéquie', 'CZ', 'CZE', 'tchequie', TRUE),
    ('Terres australes françaises', 'TF', 'ATF', 'terres-australes-francaises', TRUE),
    ('Territoire britannique de l''océan Indien', 'IO', 'IOT', 'territoire-britannique-de-l-ocean-indien', TRUE),
    ('Thaïlande', 'TH', 'THA', 'thailande', TRUE),
    ('Timor oriental', 'TL', 'TLS', 'timor-oriental', TRUE),
    ('Togo', 'TG', 'TGO', 'togo', TRUE),
    ('Tokelau', 'TK', 'TKL', 'tokelau', TRUE),
    ('Tonga', 'TO', 'TON', 'tonga', TRUE),
    ('Trinité-et-Tobago', 'TT', 'TTO', 'trinite-et-tobago', TRUE),
    ('Tunisie', 'TN', 'TUN', 'tunisie', TRUE),
    ('Turkménistan', 'TM', 'TKM', 'turkmenistan', TRUE),
    ('Turquie', 'TR', 'TUR', 'turquie', TRUE),
    ('Tuvalu', 'TV', 'TUV', 'tuvalu', TRUE),
    ('Ukraine', 'UA', 'UKR', 'ukraine', TRUE),
    ('Uruguay', 'UY', 'URY', 'uruguay', TRUE),
    ('Vanuatu', 'VU', 'VUT', 'vanuatu', TRUE),
    ('Viêt Nam', 'VN', 'VNM', 'viet-nam', TRUE),
    ('Vénézuela, république bolivarienne du', 'VE', 'VEN', 'venezuela-republique-bolivarienne-du', TRUE),
    ('Wallis et Futuna', 'WF', 'WLF', 'wallis-et-futuna', TRUE),
    ('Yémen', 'YE', 'YEM', 'yemen', TRUE),
    ('Zambie', 'ZM', 'ZMB', 'zambie', TRUE),
    ('Zimbabwe', 'ZW', 'ZWE', 'zimbabwe', TRUE),
    ('Åland, Îles', 'AX', 'ALA', 'aland-iles', TRUE),
    ('Égypte', 'EG', 'EGY', 'egypte', TRUE),
    ('Émirats arabes unis', 'AE', 'ARE', 'emirats-arabes-unis', TRUE),
    ('Équateur', 'EC', 'ECU', 'equateur', TRUE),
    ('Érythrée', 'ER', 'ERI', 'erythree', TRUE),
    ('États-Unis', 'US', 'USA', 'etats-unis', TRUE),
    ('Éthiopie', 'ET', 'ETH', 'ethiopie', TRUE),
    ('Île Bouvet', 'BV', 'BVT', 'ile-bouvet', TRUE),
    ('Île de Man', 'IM', 'IMN', 'ile-de-man', TRUE),
    ('Île Norfolk', 'NF', 'NFK', 'ile-norfolk', TRUE),
    ('Îles Caïmans', 'KY', 'CYM', 'iles-caimans', TRUE),
    ('Îles Cook', 'CK', 'COK', 'iles-cook', TRUE),
    ('Îles Féroé', 'FO', 'FRO', 'iles-feroe', TRUE),
    ('Îles Heard-et-MacDonald', 'HM', 'HMD', 'iles-heard-et-macdonald', TRUE),
    ('Îles Mariannes du Nord', 'MP', 'MNP', 'iles-mariannes-du-nord', TRUE),
    ('Îles Marshall', 'MH', 'MHL', 'iles-marshall', TRUE),
    ('Îles mineures éloignées des États-Unis', 'UM', 'UMI', 'iles-mineures-eloignees-des-etats-unis', TRUE),
    ('Îles Pitcairn', 'PN', 'PCN', 'iles-pitcairn', TRUE),
    ('Îles Turques-et-Caïques', 'TC', 'TCA', 'iles-turques-et-caiques', TRUE),
    ('Îles Vierges britanniques', 'VG', 'VGB', 'iles-vierges-britanniques', TRUE),
    ('Îles Vierges, États-Unis', 'VI', 'VIR', 'iles-vierges-etats-unis', TRUE)
ON CONFLICT (iso_code2)
DO UPDATE SET
    name = EXCLUDED.name,
    iso_code3 = EXCLUDED.iso_code3,
    slug = EXCLUDED.slug,
    is_active = EXCLUDED.is_active,
    updated_at = NOW();

COMMIT;
